# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-25 12:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='name')),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=15, verbose_name='phone')),
                ('city', models.CharField(max_length=15, verbose_name='city')),
                ('university', models.CharField(max_length=50)),
                ('current_work_place', models.CharField(max_length=50)),
                ('stars', models.PositiveIntegerField(default=0, verbose_name='network mnc')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
