# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-18 21:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(max_length=255, upload_to='avatars/', verbose_name='Avatar')),
                ('name', models.CharField(max_length=15, verbose_name='Name')),
                ('nickname', models.CharField(max_length=15, verbose_name='Nickname (Display name)')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('phone', models.CharField(max_length=15, verbose_name='Mobile phone')),
                ('city', models.CharField(max_length=15, verbose_name='Current city')),
                ('country', models.CharField(max_length=15, verbose_name='Current country')),
                ('university', models.CharField(max_length=50, verbose_name='Graduated university')),
                ('current_work_place', models.CharField(max_length=50, verbose_name='Current work place')),
                ('student_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Student number')),
                ('stars', models.PositiveIntegerField(default=0, verbose_name='Stars')),
                ('access_level', models.CharField(choices=[('N', 'New'), ('J', 'Rejected'), ('A', 'Accepted')], max_length=1, verbose_name='User access level')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
