# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-01 12:26
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,15}$', code='invalid_phone_number', message='Please enter at most 15 digits number')], verbose_name='Mobile phone'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='student_number',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,15}$', code='invalid_student_number', message='Please enter at most 15 digits number')], verbose_name='Student number'),
        ),
    ]
