# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-06 13:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20170401_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='nickname',
        ),
        migrations.AddField(
            model_name='profile',
            name='entrance_year',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator('^\\d{4}$', code='invalid_entrance_year', message='Please enter 4 digits number')], verbose_name='Entrance year'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='student_number',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$', code='invalid_student_number', message='Please enter at most 15 digits number')], verbose_name='Student number'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='university_field',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Field'),
        ),
    ]
