# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-06 13:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20170406_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='student_number',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$', code='invalid_student_number', message='Please enter at most 10 digits number')], verbose_name='Student number'),
        ),
    ]
