# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-11 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20170406_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='university_field',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Field'),
        ),
    ]
