# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-18 21:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='', verbose_name='Description')),
                ('accepted', models.BooleanField(default=False, verbose_name='Accepted')),
                ('published', models.CharField(choices=[('N', 'New'), ('R', 'Removed'), ('J', 'Rejected'), ('P', 'Published')], default='N', max_length=1, verbose_name='Publish state')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.TextField(default='', verbose_name='Description')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Views')),
                ('published', models.CharField(choices=[('N', 'New'), ('R', 'Removed'), ('J', 'Rejected'), ('P', 'Published')], max_length=1, verbose_name='Publish state')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='Upload time')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='UniversityField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='fields',
            field=models.ManyToManyField(to='forum.UniversityField', verbose_name='Fields'),
        ),
        migrations.AddField(
            model_name='question',
            name='stars',
            field=models.ManyToManyField(related_name='question_user_stars', to=settings.AUTH_USER_MODEL, verbose_name='Stars'),
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(to='forum.Tag', verbose_name='tags'),
        ),
        migrations.AddField(
            model_name='question',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='stars',
            field=models.ManyToManyField(related_name='answer_user_stars', to=settings.AUTH_USER_MODEL, verbose_name='Stars'),
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
