# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-25 12:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='')),
                ('accepted', models.BooleanField(default=False)),
                ('published', models.CharField(choices=[('N', 'New'), ('J', 'Rejected'), ('P', 'Published')], default='N', max_length=1, verbose_name='publish state')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(default='')),
                ('stars', models.PositiveIntegerField(default=0)),
                ('views', models.PositiveIntegerField(default=0)),
                ('published', models.CharField(choices=[('N', 'New'), ('J', 'Rejected'), ('P', 'Published')], max_length=1, verbose_name='publish state')),
                ('upload_time', models.DateTimeField(default=datetime.date.today, verbose_name='upload time')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Question'),
        ),
    ]
