# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-06 13:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20170406_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='fields',
            new_name='subjects',
        ),
    ]
