# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-06 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20170406_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='subjects',
            field=models.ManyToManyField(to='forum.Subject', verbose_name='Subjects'),
        ),
    ]
