# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-16 12:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20170406_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='upload_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Upload time'),
        ),
    ]
